on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install LLVM/Clang
      run: |
        choco install llvm --version=21.1.0 -y
        refreshenv

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja" -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build build --config Release
